openapi: 3.2.0
info:
  title: VTex Catalog SKU File API
  description: "\n> Check the new [Catalog onboarding guide](https://developers.vtex.com/docs/guides/catalog-overview). We created this guide to improve the onboarding experience for developers at VTEX. It assembles all documentation on our Developer Portal about Catalog and is organized by focusing on the developer's journey.\n\nThe Catalog API is a crucial part of the VTEX ecommerce platform, empowering developers to seamlessly manage product information. It enables the creation, modification, and deletion of product details, including attributes like images and specifications. SKU management covers product variations. The Catalog API also supports organizing products into categories and managing brands. \n\n## Index\n\n### Category\n\n* `GET` [Get category tree](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog_system/pub/category/tree/-categoryLevels-)\n* `GET` [Get category by ID](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog/pvt/category/-categoryId-)\n* `PUT` [Update category](https://developers.vtex.com/docs/api-reference/catalog-api#put-/api/catalog/pvt/category/-categoryId-)\n* `POST` [Create category](https://developers.vtex.com/docs/api-reference/catalog-api#post-/api/catalog/pvt/category)\n\n### Category specification\n\n* `GET` [Get specifications By category ID](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog_system/pub/specification/field/listByCategoryId/-categoryId-)\n* `GET` [Get specifications tree By category ID](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog_system/pub/specification/field/listTreeByCategoryId/-categoryId-)\n\n### Brand\n\n* `GET` [Get brand List](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog_system/pvt/brand/list)\n* `GET` [Get brand List Per Page](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog_system/pvt/brand/pagedlist)\n* `GET` [Get brand](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog_system/pvt/brand/-brandId-)\n* `POST` [Create brand](https://developers.vtex.com/docs/api-reference/catalog-api#post-/api/catalog/pvt/brand)\n* `GET` [Get brand and context](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog/pvt/brand/-brandId-)\n* `PUT` [Update brand](https://developers.vtex.com/docs/api-reference/catalog-api#put-/api/catalog/pvt/brand/-brandId-)\n* `DELETE` [Delete brand](https://developers.vtex.com/docs/api-reference/catalog-api#delete-/api/catalog/pvt/brand/-brandId-)\n\n### Specification group\n\n* `GET` [List specification Group by category](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog_system/pvt/specification/groupbycategory/-categoryId-)\n* `GET` [Get specification Group](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog_system/pub/specification/groupGet/-groupId-)\n* `POST` [Create specification Group](https://developers.vtex.com/docs/api-reference/catalog-api#post-/api/catalog/pvt/specificationgroup)\n* `PUT` [Update specification Group](https://developers.vtex.com/docs/api-reference/catalog-api#put-/api/catalog/pvt/specificationgroup/-groupId-)\n\n### Specification\n\n* `GET` [Get specification](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog/pvt/specification/-specificationId-)\n* `PUT` [Update specification](https://developers.vtex.com/docs/api-reference/catalog-api#put-/api/catalog/pvt/specification/-specificationId-)\n* `POST` [Create specification](https://developers.vtex.com/docs/api-reference/catalog-api#post-/api/catalog/pvt/specification)\n\n### Specification Field\n\n* `GET` [Get specification Field](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog_system/pub/specification/fieldGet/-fieldId-)\n* `POST` [Create specification Field](https://developers.vtex.com/docs/api-reference/catalog-api#post-/api/catalog_system/pvt/specification/field)\n* `PUT` [Update specification Field](https://developers.vtex.com/docs/api-reference/catalog-api#put-/api/catalog_system/pvt/specification/field)\n\n### Non-structured specification\n\n* `GET` [Get non-structured specification by ID](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog/pvt/specification/nonstructured/-Id-)\n* `DELETE` [Delete non-structured specification](https://developers.vtex.com/docs/api-reference/catalog-api#delete-/api/catalog/pvt/specification/nonstructured/-Id-)\n* `GET` [Get non-structured specification by SKU ID](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog/pvt/specification/nonstructured)\n* `DELETE` [Delete non-structured specification by SKU ID](https://developers.vtex.com/docs/api-reference/catalog-api#delete-/api/catalog/pvt/specification/nonstructured)\n\n### Specification value\n\n* `GET` [Get specification value](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog/pvt/specificationvalue/-specificationValueId-)\n* `PUT` [Update specification value](https://developers.vtex.com/docs/api-reference/catalog-api#put-/api/catalog/pvt/specificationvalue/-specificationValueId-)\n* `POST` [Create specification value](https://developers.vtex.com/docs/api-reference/catalog-api#post-/api/catalog/pvt/specificationvalue)\n\n### Specification Field Value\n\n* `GET` [Get specification field value](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog_system/pvt/specification/fieldValue/-fieldValueId-)\n* `GET` [Get specification values by field ID](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog_system/pub/specification/fieldvalue/-fieldId-)\n* `POST` [Create specification field value](https://developers.vtex.com/docs/api-reference/catalog-api#post-/api/catalog_system/pvt/specification/fieldValue)\n* `PUT` [Update specification field value](https://developers.vtex.com/docs/api-reference/catalog-api#put-/api/catalog_system/pvt/specification/fieldValue)\n\n### Product\n\n* `GET` [Get product and SKU IDs](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog_system/pvt/products/GetProductAndSkuIds)\n* `GET` [Get product by ID](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog/pvt/product/-productId-)\n* `PUT` [Update product](https://developers.vtex.com/docs/api-reference/catalog-api#put-/api/catalog/pvt/product/-productId-)\n* `GET` [Get product and its general context](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog_system/pvt/products/productget/-productId-)\n* `GET` [Get product by RefId](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog_system/pvt/products/productgetbyrefid/-refId-)\n* `GET` [Get product's SKUs by product ID](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog_system/pub/products/variations/-productId-)\n* `GET` [Get product Review Rate by product ID](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/addon/pvt/review/GetProductRate/-productId-)\n* `POST` [Create product with category and brand](https://developers.vtex.com/docs/api-reference/catalog-api#post-/api/catalog/pvt/product)\n\n### Product specification\n\n* `GET` [Get product specifications by product ID](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog_system/pvt/products/-productId-/specification)\n* `POST` [Update product specification by product ID](https://developers.vtex.com/docs/api-reference/catalog-api#post-/api/catalog_system/pvt/products/-productId-/specification)\n* `GET` [Get product specification and its information by product ID](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog/pvt/product/-productId-/specification)\n* `POST` [Associate product specification](https://developers.vtex.com/docs/api-reference/catalog-api#post-/api/catalog/pvt/product/-productId-/specification)\n* `DELETE` [Delete all product specifications by product ID](https://developers.vtex.com/docs/api-reference/catalog-api#delete-/api/catalog/pvt/product/-productId-/specification)\n* `DELETE` [Delete a product specification](https://developers.vtex.com/docs/api-reference/catalog-api#delete-/api/catalog/pvt/product/-productId-/specification/-specificationId-)\n* `PUT` [Associate product specification using specification name and group name](https://developers.vtex.com/docs/api-reference/catalog-api#put-/api/catalog/pvt/product/-productId-/specificationvalue)\n\n### SKU\n\n* `GET` [List all SKU IDs](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog_system/pvt/sku/stockkeepingunitids)\n* `GET` [SKU and context](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog_system/pvt/sku/stockkeepingunitbyid/-skuId-)\n* `GET` [Get SKU by RefId](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog/pvt/stockkeepingunit)\n* `POST` [Create SKU](https://developers.vtex.com/docs/api-reference/catalog-api#post-/api/catalog/pvt/stockkeepingunit)\n* `GET` [Get SKU ID by Reference ID](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog_system/pvt/sku/stockkeepingunitidbyrefid/-refId-)\n* `GET` [Get SKU by Alternate ID](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog_system/pvt/sku/stockkeepingunitbyalternateId/-alternateId-)\n* `GET` [Get SKU list by product ID](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog_system/pvt/sku/stockkeepingunitByProductId/-productId-)\n* `POST` [Retrieve SKU ID list by Reference ID list](https://developers.vtex.com/docs/api-reference/catalog-api#post-/api/catalog_system/pub/sku/stockkeepingunitidsbyrefids)\n* `GET` [Get SKU](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog/pvt/stockkeepingunit/-skuId-)\n* `PUT` [Update SKU](https://developers.vtex.com/docs/api-reference/catalog-api#put-/api/catalog/pvt/stockkeepingunit/-skuId-)\n\n### SKU specification\n\n* `GET` [Get SKU specifications](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog/pvt/stockkeepingunit/-skuId-/specification)\n* `POST` [Associate SKU specification](https://developers.vtex.com/docs/api-reference/catalog-api#post-/api/catalog/pvt/stockkeepingunit/-skuId-/specification)\n* `PUT` [Update SKU specification](https://developers.vtex.com/docs/api-reference/catalog-api#put-/api/catalog/pvt/stockkeepingunit/-skuId-/specification)\n* `DELETE` [Delete all SKU specifications](https://developers.vtex.com/docs/api-reference/catalog-api#delete-/api/catalog/pvt/stockkeepingunit/-skuId-/specification)\n* `DELETE` [Delete SKU specification](https://developers.vtex.com/docs/api-reference/catalog-api#delete-/api/catalog/pvt/stockkeepingunit/-skuId-/specification/-specificationId-)\n* `PUT` [Associate SKU specification using specification name and group name](https://developers.vtex.com/docs/api-reference/catalog-api#put-/api/catalog/pvt/stockkeepingunit/-skuId-/specificationvalue)\n\n### SKU file\n\n* `GET` [Get SKU files](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog/pvt/stockkeepingunit/-skuId-/file)\n* `POST` [Create SKU file](https://developers.vtex.com/docs/api-reference/catalog-api#post-/api/catalog/pvt/stockkeepingunit/-skuId-/file)\n* `DELETE` [Delete All SKU files](https://developers.vtex.com/docs/api-reference/catalog-api#delete-/api/catalog/pvt/stockkeepingunit/-skuId-/file)\n* `PUT` [Update SKU file](https://developers.vtex.com/docs/api-reference/catalog-api#put-/api/catalog/pvt/stockkeepingunit/-skuId-/file/-skuFileId-)\n* `DELETE` [Delete SKU Image File](https://developers.vtex.com/docs/api-reference/catalog-api#delete-/api/catalog/pvt/stockkeepingunit/-skuId-/file/-skuFileId-)\n* `PUT` [Copy Files from an SKU to another SKU](https://developers.vtex.com/docs/api-reference/catalog-api#put-/api/catalog/pvt/stockkeepingunit/copy/-skuIdfrom-/-skuIdto-/file)\n* `DELETE` [Disassociate SKU file](https://developers.vtex.com/docs/api-reference/catalog-api#delete-/api/catalog/pvt/stockkeepingunit/disassociate/-skuId-/file/-skuFileId-)\n\n### SKU complement\n\n* `GET` [Get SKU complement by SKU ID](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog/pvt/stockkeepingunit/-skuId-/complement)\n* `GET` [Get SKU complements by Complement Type ID](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog/pvt/stockkeepingunit/-skuId-/complement/-complementTypeId-)\n* `GET` [Get SKU complements by type](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog_system/pvt/sku/complements/-parentSkuId-/-type-)\n* `POST` [Create SKU complement](https://developers.vtex.com/docs/api-reference/catalog-api#post-/api/catalog/pvt/skucomplement)\n* `GET` [Get SKU complement by SKU complement ID](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog/pvt/skucomplement/-skuComplementId-)\n* `DELETE` [Delete SKU complement by SKU complement ID](https://developers.vtex.com/docs/api-reference/catalog-api#delete-/api/catalog/pvt/skucomplement/-skuComplementId-)\n\n### SKU EAN\n\n* `GET` [Get SKU by EAN](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog_system/pvt/sku/stockkeepingunitbyean/-ean-)\n* `GET` [Get EAN by SKU ID](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog/pvt/stockkeepingunit/-skuId-/ean)\n* `DELETE` [Delete all SKU EAN values](https://developers.vtex.com/docs/api-reference/catalog-api#delete-/api/catalog/pvt/stockkeepingunit/-skuId-/ean)\n* `POST` [Create SKU EAN](https://developers.vtex.com/docs/api-reference/catalog-api#post-/api/catalog/pvt/stockkeepingunit/-skuId-/ean/-ean-)\n* `DELETE` [Delete SKU EAN](https://developers.vtex.com/docs/api-reference/catalog-api#delete-/api/catalog/pvt/stockkeepingunit/-skuId-/ean/-ean-)\n\n### Attachment\n\n* `GET` [Get attachment](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog/pvt/attachment/-attachmentid-)\n* `PUT` [Update attachment](https://developers.vtex.com/docs/api-reference/catalog-api#put-/api/catalog/pvt/attachment/-attachmentid-)\n* `DELETE` [Delete attachment](https://developers.vtex.com/docs/api-reference/catalog-api#delete-/api/catalog/pvt/attachment/-attachmentid-)\n* `POST` [Create attachment](https://developers.vtex.com/docs/api-reference/catalog-api#post-/api/catalog/pvt/attachment)\n* `GET` [Get all attachments](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog/pvt/attachments)\n\n### SKU attachment\n\n* `POST` [Associate SKU attachment](https://developers.vtex.com/docs/api-reference/catalog-api#post-/api/catalog/pvt/skuattachment)\n* `DELETE` [Dissociate attachments and SKUs](https://developers.vtex.com/docs/api-reference/catalog-api#delete-/api/catalog/pvt/skuattachment)\n* `GET` [Get SKU attachments by SKU ID](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog/pvt/stockkeepingunit/-skuId-/attachment)\n* `DELETE` [Delete SKU attachment by Attachment Association ID](https://developers.vtex.com/docs/api-reference/catalog-api#delete-/api/catalog/pvt/skuattachment/-skuAttachmentAssociationId-)\n* `POST` [Associate attachments to an SKU](https://developers.vtex.com/docs/api-reference/catalog-api#post-/api/catalog_system/pvt/sku/associateattachments)\n\n### SKU service\n\n* `GET` [Get SKU service](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog/pvt/skuservice/-skuServiceId-)\n* `PUT` [Update SKU service](https://developers.vtex.com/docs/api-reference/catalog-api#put-/api/catalog/pvt/skuservice/-skuServiceId-)\n* `DELETE` [Dissociate SKU service](https://developers.vtex.com/docs/api-reference/catalog-api#delete-/api/catalog/pvt/skuservice/-skuServiceId-)\n* `POST` [Associate SKU service](https://developers.vtex.com/docs/api-reference/catalog-api#post-/api/catalog/pvt/skuservice)\n\n### SKU service attachment\n\n* `POST` [Associate SKU service attachment](https://developers.vtex.com/docs/api-reference/catalog-api#post-/api/catalog/pvt/skuservicetypeattachment)\n* `DELETE` [Dissociate Attachment by Attachment ID or SKU service type ID](https://developers.vtex.com/docs/api-reference/catalog-api#delete-/api/catalog/pvt/skuservicetypeattachment)\n* `DELETE` [Dissociate Attachment from SKU service type](https://developers.vtex.com/docs/api-reference/catalog-api#delete-/api/catalog/pvt/skuservicetypeattachment/-skuServiceTypeAttachmentId-)\n\n### SKU service type\n\n* `POST` [Create SKU service type](https://developers.vtex.com/docs/api-reference/catalog-api#post-/api/catalog/pvt/skuservicetype)\n* `GET` [Get SKU service type](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog/pvt/skuservicetype/-skuServiceTypeId-)\n* `PUT` [Update SKU service type](https://developers.vtex.com/docs/api-reference/catalog-api#put-/api/catalog/pvt/skuservicetype/-skuServiceTypeId-)\n* `DELETE` [Delete SKU service type](https://developers.vtex.com/docs/api-reference/catalog-api#delete-/api/catalog/pvt/skuservicetype/-skuServiceTypeId-)\n\n### SKU service value\n\n* `POST` [Create SKU service value](https://developers.vtex.com/docs/api-reference/catalog-api#post-/api/catalog/pvt/skuservicevalue)\n* `GET` [Get SKU service value](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog/pvt/skuservicevalue/-skuServiceValueId-)\n* `PUT` [Update SKU service value](https://developers.vtex.com/docs/api-reference/catalog-api#put-/api/catalog/pvt/skuservicevalue/-skuServiceValueId-)\n* `DELETE` [Delete SKU service value](https://developers.vtex.com/docs/api-reference/catalog-api#delete-/api/catalog/pvt/skuservicevalue/-skuServiceValueId-)\n\n### SKU kit\n\n* `GET` [Get SKU kit by SKU ID or Parent SKU ID](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog/pvt/stockkeepingunitkit)\n* `POST` [Create SKU kit](https://developers.vtex.com/docs/api-reference/catalog-api#post-/api/catalog/pvt/stockkeepingunitkit)\n* `DELETE` [Delete SKU kit by SKU ID or Parent SKU ID](https://developers.vtex.com/docs/api-reference/catalog-api#delete-/api/catalog/pvt/stockkeepingunitkit)\n* `GET` [Get SKU kit](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog/pvt/stockkeepingunitkit/-kitId-)\n* `DELETE` [Delete SKU kit by KitId](https://developers.vtex.com/docs/api-reference/catalog-api#delete-/api/catalog/pvt/stockkeepingunitkit/-kitId-)\n\n### SKU seller\n\n* `GET` [Get details of a seller's SKU](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog_system/pvt/skuseller/-sellerId-/-sellerSkuId-)\n* `POST` [Remove a seller's SKU binding](https://developers.vtex.com/docs/api-reference/catalog-api#post-/api/catalog_system/pvt/skuseller/remove/-sellerId-/-sellerSkuId-)\n* `POST` [Change notification with Seller ID and Seller SKU ID](https://developers.vtex.com/docs/api-reference/catalog-api#post-/api/catalog_system/pvt/skuseller/changenotification/-sellerId-/-sellerSkuId-)\n* `POST` [Change notification with SKU ID](https://developers.vtex.com/docs/api-reference/catalog-api#post-/api/catalog_system/pvt/skuseller/changenotification/-skuId-)\n\n### Similar category\n\n* `GET` [Get Similar Categories](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog/pvt/product/-productId-/similarcategory/)\n* `POST` [Add Similar category](https://developers.vtex.com/docs/api-reference/catalog-api#post-/api/catalog/pvt/product/-productId-/similarcategory/-categoryId-)\n* `DELETE` [Delete Similar category](https://developers.vtex.com/docs/api-reference/catalog-api#delete-/api/catalog/pvt/product/-productId-/similarcategory/-categoryId-)\n\n### Collection Beta\n\n* `GET` [Get All Collections](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog_system/pvt/collection/search)\n* `GET` [Get All Inactive Collections](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog/pvt/collection/inactive)\n* `POST` [Create Collection](https://developers.vtex.com/docs/api-reference/catalog-api#post-/api/catalog/pvt/collection/)\n* `GET` [Get Collections by search terms](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog_system/pvt/collection/search/-searchTerms-)\n* `GET` [Import Collection file example](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog/pvt/collection/stockkeepingunit/importfileexample)\n* `POST` [Add products to Collection by imported file](https://developers.vtex.com/docs/api-reference/catalog-api#post-/api/catalog/pvt/collection/-collectionId-/stockkeepingunit/importinsert)\n* `POST` [Remove products from Collection by imported file](https://developers.vtex.com/docs/api-reference/catalog-api#post-/api/catalog/pvt/collection/-collectionId-/stockkeepingunit/importexclude)\n* `GET` [Get products from a collection](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog/pvt/collection/-collectionId-/products)\n\n### Legacy collection\n\n* `GET` [Get Collection](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog/pvt/collection/-collectionId-)\n* `PUT` [Update Collection](https://developers.vtex.com/docs/api-reference/catalog-api#put-/api/catalog/pvt/collection/-collectionId-)\n* `DELETE` [Delete Collection](https://developers.vtex.com/docs/api-reference/catalog-api#delete-/api/catalog/pvt/collection/-collectionId-)\n* `POST` [Create Collection](https://developers.vtex.com/docs/api-reference/catalog-api#post-/api/catalog/pvt/collection)\n\n### Legacy subcollection\n\n* `POST` [Add SKU to Subcollection](https://developers.vtex.com/docs/api-reference/catalog-api#post-/api/catalog/pvt/subcollection/-subCollectionId-/stockkeepingunit)\n* `DELETE` [Delete SKU from Subcollection](https://developers.vtex.com/docs/api-reference/catalog-api#delete-/api/catalog/pvt/subcollection/-subCollectionId-/stockkeepingunit/-skuId-)\n* `POST` [Associate category to Subcollection](https://developers.vtex.com/docs/api-reference/catalog-api#post-/api/catalog/pvt/subcollection/-subCollectionId-/category)\n* `DELETE` [Delete category from Subcollection](https://developers.vtex.com/docs/api-reference/catalog-api#delete-/api/catalog/pvt/subcollection/-subCollectionId-/brand/-categoryId-)\n* `POST` [Associate brand to Subcollection](https://developers.vtex.com/docs/api-reference/catalog-api#post-/api/catalog/pvt/subcollection/-subCollectionId-/brand)\n* `DELETE` [Delete brand from Subcollection](https://developers.vtex.com/docs/api-reference/catalog-api#delete-/api/catalog/pvt/subcollection/-subCollectionId-/brand/-brandId-)\n* `GET` [Get subcollection by collection ID](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog/pvt/collection/-collectionId-/subcollection)\n* `GET` [Get Subcollection](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog/pvt/subcollection/-subCollectionId-)\n* `PUT` [Update Subcollection](https://developers.vtex.com/docs/api-reference/catalog-api#put-/api/catalog/pvt/subcollection/-subCollectionId-)\n* `DELETE` [Delete Subcollection](https://developers.vtex.com/docs/api-reference/catalog-api#delete-/api/catalog/pvt/subcollection/-subCollectionId-)\n* `POST` [Create Subcollection](https://developers.vtex.com/docs/api-reference/catalog-api#post-/api/catalog/pvt/subcollection)\n* `POST` [Reposition SKU on the Subcollection](https://developers.vtex.com/docs/api-reference/catalog-api#post-/api/catalog/pvt/collection/-collectionId-/position)\n\n### Seller\n\n* `GET` [Get Seller List](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog_system/pvt/seller/list)\n* `GET` [Get Seller by ID](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog_system/pvt/seller/-sellerId-)\n* `PUT` [Update Seller](https://developers.vtex.com/docs/api-reference/catalog-api#put-/api/catalog_system/pvt/seller)\n* `POST` [Create Seller](https://developers.vtex.com/docs/api-reference/catalog-api#post-/api/catalog_system/pvt/seller)\n* `GET` [Get Seller by ID](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog_system/pvt/sellers/-sellerId-)\n\n### Supplier\n\n* `POST` [Create Supplier](https://developers.vtex.com/docs/api-reference/catalog-api#post-/api/catalog/pvt/supplier)\n* `PUT` [Update Supplier](https://developers.vtex.com/docs/api-reference/catalog-api#put-/api/catalog/pvt/supplier/-supplierId-)\n* `DELETE` [Delete Supplier](https://developers.vtex.com/docs/api-reference/catalog-api#delete-/api/catalog/pvt/supplier/-supplierId-)\n\n### Trade policy\n\n* `GET` [Get Trade Policies by product ID](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog/pvt/product/-productId-/salespolicy)\n* `POST` [Associate product with trade policy](https://developers.vtex.com/docs/api-reference/catalog-api#post-/api/catalog/pvt/product/-productId-/salespolicy/-tradepolicyId-)\n* `DELETE` [Remove product from trade policy](https://developers.vtex.com/docs/api-reference/catalog-api#delete-/api/catalog/pvt/product/-productId-/salespolicy/-tradepolicyId-)\n* `GET` [List all SKUs of a trade policy](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog_system/pvt/sku/stockkeepingunitidsbysaleschannel)\n\n### Sales channel\n\n* `GET` [Get Sales channel List](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog_system/pvt/saleschannel/list)\n* `GET` [Get Sales channel by ID](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog_system/pub/saleschannel/-salesChannelId-)\n\n### Product indexing\n\n* `GET` [Get product Indexed Information](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog_system/pvt/products/GetIndexedInfo/-productId-)\n\n### Commercial conditions\n\n* `GET` [Get all commercial conditions](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog_system/pvt/commercialcondition/list)\n* `GET` [Get commercial condition](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/catalog_system/pvt/commercialcondition/-commercialConditionId-)\n\n### Gift list\n\n* `GET` [Get gift list](https://developers.vtex.com/docs/api-reference/catalog-api#get-/api/addon/pvt/giftlist/get/-listId-)"
  version: '1.0'
servers:
- url: https://{accountName}.{environment}.com.br
  description: VTEX server URL.
  variables:
    accountName:
      description: Name of the VTEX account. Used as part of the URL.
      default: apiexamples
    environment:
      description: Environment to use. Used as part of the URL.
      enum:
      - vtexcommercestable
      default: vtexcommercestable
security:
- appKey: []
  appToken: []
- VtexIdclientAutCookie: []
tags:
- name: SKU File
paths:
  /api/catalog/pvt/stockkeepingunit/{skuId}/file:
    get:
      tags:
      - SKU File
      summary: VTex Get SKU files
      description: 'Retrieves general information about all files in the SKU.


        ## Permissions


        Any user or [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys) must have at least one of the appropriate [License Manager resources](https://help.vtex.com/en/tutorial/license-manager-resources--3q6ztrC8YynQf6rdc6euk3) to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:


        | **Product** | **Category** | **Resource** |

        | --------------- | ----------------- | ----------------- |

        | Catalog | Content | **SKUs** |


        There are no applicable [predefined roles](https://help.vtex.com/en/tutorial/predefined-roles--jGDurZKJHvHJS13LnO7Dy) for this resource list. You must [create a custom role](https://help.vtex.com/en/tutorial/roles--7HKK5Uau2H6wxE1rH5oRbc#creating-a-role) and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see [Authentication overview](https://developers.vtex.com/docs/guides/authentication).


        >❗ To prevent integrations from having excessive permissions, consider the [best practices for managing app keys](https://help.vtex.com/en/tutorial/best-practices-application-keys--7b6nD1VMHa49aI5brlOvJm) when assigning License Manager roles to integrations.'
      parameters:
      - $ref: '#/components/parameters/Content-Type'
      - $ref: '#/components/parameters/Accept'
      - name: skuId
        in: path
        required: true
        description: SKU's unique numerical identifier.
        schema:
          type: integer
          example: 1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                description: Array with objects containing SKU files information.
                items:
                  type: object
                  description: Object containing each SKU file's information.
                  properties:
                    Id:
                      type: integer
                      description: Unique identifier of the association of the image to the SKU.
                    ArchiveId:
                      type: integer
                      description: Unique identifier of the image.
                    SkuId:
                      type: integer
                      description: Unique identifier of the SKU.
                    Name:
                      type: string
                      description: Image name.
                    IsMain:
                      type: boolean
                      description: Defines if the image is the main image of the SKU.
                    Label:
                      type:
                      - string
                      - 'null'
                      description: Image label.
              example:
              - Id: 549
                ArchiveId: 155485
                SkuId: 310118490
                Name: chimera-cat-quimera-5
                IsMain: true
                Label: miau
              - Id: 550
                ArchiveId: 155486
                SkuId: 310118490
                Name: Gato-siames
                IsMain: false
                Label: Gato siames
              - Id: 555
                ArchiveId: 155491
                SkuId: 310118490
                Name: Cat-Sleeping-Pics
                IsMain: false
                Label: null
    post:
      tags:
      - SKU File
      summary: VTex Create SKU file
      description: 'Creates a new image for an SKU based on its URL or on a form-data request body.


        ## Permissions


        Any user or [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys) must have at least one of the appropriate [License Manager resources](https://help.vtex.com/en/tutorial/license-manager-resources--3q6ztrC8YynQf6rdc6euk3) to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:


        | **Product** | **Category** | **Resource** |

        | --------------- | ----------------- | ----------------- |

        | Catalog | Content | **SKUs** |


        There are no applicable [predefined roles](https://help.vtex.com/en/tutorial/predefined-roles--jGDurZKJHvHJS13LnO7Dy) for this resource list. You must [create a custom role](https://help.vtex.com/en/tutorial/roles--7HKK5Uau2H6wxE1rH5oRbc#creating-a-role) and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see [Authentication overview](https://developers.vtex.com/docs/guides/authentication).


        >❗ To prevent integrations from having excessive permissions, consider the [best practices for managing app keys](https://help.vtex.com/en/tutorial/best-practices-application-keys--7b6nD1VMHa49aI5brlOvJm) when assigning License Manager roles to integrations.'
      parameters:
      - $ref: '#/components/parameters/Content-Type'
      - $ref: '#/components/parameters/Accept'
      - name: skuId
        in: path
        required: true
        description: SKU's unique numerical identifier.
        schema:
          type: integer
          example: 123456
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SKUFileURL'
          form-data:
            schema:
              $ref: '#/components/schemas/SKUFile'
      responses:
        '200':
          description: OK
          content:
            application/json:
              example:
                Id: 625
                ArchiveId: 155569
                SkuId: 123456
                IsMain: true
                Label: Main
              schema:
                type: object
                properties:
                  Id:
                    type: integer
                    description: ID of the association of the SKU and the image (`SkuFileId`). This is the ID that is used to update or delete it.
                  ArchiveId:
                    type: integer
                    description: Unique identifier of the image file.
                  SkuId:
                    type: integer
                    description: SKU ID.
                  IsMain:
                    type: boolean
                    description: Set the image as the main image for the product.
                  Label:
                    type: string
                    description: Image label.
    delete:
      tags:
      - SKU File
      summary: VTex Delete all SKU files
      description: 'Deletes all SKU image files.


        ## Permissions


        Any user or [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys) must have at least one of the appropriate [License Manager resources](https://help.vtex.com/en/tutorial/license-manager-resources--3q6ztrC8YynQf6rdc6euk3) to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:


        | **Product** | **Category** | **Resource** |

        | --------------- | ----------------- | ----------------- |

        | Catalog | Content | **SKUs** |


        There are no applicable [predefined roles](https://help.vtex.com/en/tutorial/predefined-roles--jGDurZKJHvHJS13LnO7Dy) for this resource list. You must [create a custom role](https://help.vtex.com/en/tutorial/roles--7HKK5Uau2H6wxE1rH5oRbc#creating-a-role) and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see [Authentication overview](https://developers.vtex.com/docs/guides/authentication).


        >❗ To prevent integrations from having excessive permissions, consider the [best practices for managing app keys](https://help.vtex.com/en/tutorial/best-practices-application-keys--7b6nD1VMHa49aI5brlOvJm) when assigning License Manager roles to integrations.'
      parameters:
      - $ref: '#/components/parameters/Content-Type'
      - $ref: '#/components/parameters/Accept'
      - name: skuId
        in: path
        required: true
        description: SKU's unique numerical identifier.
        schema:
          type: integer
          example: 1
      responses:
        '200':
          description: OK
  /api/catalog/pvt/stockkeepingunit/{skuId}/file/{skuFileId}:
    put:
      tags:
      - SKU File
      summary: VTex Update SKU file
      description: 'Updates a new image on an SKU based on its URL or on a form-data request body.


        ## Permissions


        Any user or [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys) must have at least one of the appropriate [License Manager resources](https://help.vtex.com/en/tutorial/license-manager-resources--3q6ztrC8YynQf6rdc6euk3) to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:


        | **Product** | **Category** | **Resource** |

        | --------------- | ----------------- | ----------------- |

        | Catalog | Content | **SKUs** |


        There are no applicable [predefined roles](https://help.vtex.com/en/tutorial/predefined-roles--jGDurZKJHvHJS13LnO7Dy) for this resource list. You must [create a custom role](https://help.vtex.com/en/tutorial/roles--7HKK5Uau2H6wxE1rH5oRbc#creating-a-role) and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see [Authentication overview](https://developers.vtex.com/docs/guides/authentication).


        >❗ To prevent integrations from having excessive permissions, consider the [best practices for managing app keys](https://help.vtex.com/en/tutorial/best-practices-application-keys--7b6nD1VMHa49aI5brlOvJm) when assigning License Manager roles to integrations.'
      parameters:
      - $ref: '#/components/parameters/Content-Type'
      - $ref: '#/components/parameters/Accept'
      - name: skuId
        in: path
        required: true
        description: SKU's unique numerical identifier.
        schema:
          type: integer
          example: 123456
      - name: skuFileId
        in: path
        required: true
        description: ID of the association of the SKU and the image, which can be obtained by placing a request to the [Get SKU file](https://developers.vtex.com/vtex-rest-api/reference/catalog-api-get-sku-file) endpoint and copying the `Id` field.
        schema:
          type: integer
          example: 517
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SKUFileURL'
          form-data:
            schema:
              $ref: '#/components/schemas/SKUFile'
      responses:
        '200':
          description: OK
          content:
            application/json:
              example:
                Id: 625
                ArchiveId: 155569
                SkuId: 123456
                IsMain: true
                Label: Main
              schema:
                type: object
                properties:
                  Id:
                    type: integer
                    description: ID of the association of the SKU and the image (`SkuFileId`). This is the ID that is used to update or delete it.
                  ArchiveId:
                    type: integer
                    description: Unique identifier of the image file.
                  SkuId:
                    type: integer
                    description: SKU ID.
                  IsMain:
                    type: boolean
                    description: Set the image as the main image for the product.
                  Label:
                    type: string
                    description: Image label.
    delete:
      tags:
      - SKU File
      summary: VTex Delete SKU image file
      description: 'Deletes a specific SKU image file.


        ## Permissions


        Any user or [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys) must have at least one of the appropriate [License Manager resources](https://help.vtex.com/en/tutorial/license-manager-resources--3q6ztrC8YynQf6rdc6euk3) to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:


        | **Product** | **Category** | **Resource** |

        | --------------- | ----------------- | ----------------- |

        | Catalog | Content | **SKUs** |


        There are no applicable [predefined roles](https://help.vtex.com/en/tutorial/predefined-roles--jGDurZKJHvHJS13LnO7Dy) for this resource list. You must [create a custom role](https://help.vtex.com/en/tutorial/roles--7HKK5Uau2H6wxE1rH5oRbc#creating-a-role) and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see [Authentication overview](https://developers.vtex.com/docs/guides/authentication).


        >❗ To prevent integrations from having excessive permissions, consider the [best practices for managing app keys](https://help.vtex.com/en/tutorial/best-practices-application-keys--7b6nD1VMHa49aI5brlOvJm) when assigning License Manager roles to integrations.'
      parameters:
      - $ref: '#/components/parameters/Content-Type'
      - $ref: '#/components/parameters/Accept'
      - name: skuId
        in: path
        required: true
        description: SKU's unique numerical identifier.
        schema:
          type: integer
          example: 1
      - name: skuFileId
        in: path
        required: true
        description: ID of the association of the SKU and the image, which can be obtained by placing a request to the [Get SKU file](https://developers.vtex.com/vtex-rest-api/reference/catalog-api-get-sku-file) endpoint and copying the `Id` field.
        schema:
          type: integer
          example: 1
      responses:
        '200':
          description: OK
  /api/catalog/pvt/stockkeepingunit/copy/{skuIdfrom}/{skuIdto}/file:
    put:
      tags:
      - SKU File
      summary: VTex Copy files from an SKU to another SKU
      description: 'Copy all existing files from an SKU to another SKU.


        ## Permissions


        Any user or [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys) must have at least one of the appropriate [License Manager resources](https://help.vtex.com/en/tutorial/license-manager-resources--3q6ztrC8YynQf6rdc6euk3) to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:


        | **Product** | **Category** | **Resource** |

        | --------------- | ----------------- | ----------------- |

        | Catalog | Content | **SKUs** |


        There are no applicable [predefined roles](https://help.vtex.com/en/tutorial/predefined-roles--jGDurZKJHvHJS13LnO7Dy) for this resource list. You must [create a custom role](https://help.vtex.com/en/tutorial/roles--7HKK5Uau2H6wxE1rH5oRbc#creating-a-role) and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see [Authentication overview](https://developers.vtex.com/docs/guides/authentication).


        >❗ To prevent integrations from having excessive permissions, consider the [best practices for managing app keys](https://help.vtex.com/en/tutorial/best-practices-application-keys--7b6nD1VMHa49aI5brlOvJm) when assigning License Manager roles to integrations.'
      parameters:
      - $ref: '#/components/parameters/Content-Type'
      - $ref: '#/components/parameters/Accept'
      - name: skuIdfrom
        in: path
        required: true
        description: __Origin__ SKU's unique numerical identifier.
        schema:
          type: integer
          example: 1
      - name: skuIdto
        in: path
        required: true
        description: __Target__ SKU's unique numerical identifier.
        schema:
          type: integer
          example: 2
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                description: Array with objects containing information about each of the target SKU's files.
                items:
                  type: object
                  description: Object containing each SKU file's information.
                  properties:
                    Id:
                      type: integer
                      description: Unique identifier of the association of the image to the SKU.
                    ArchiveId:
                      type: integer
                      description: Unique identifier of the image file.
                    SkuId:
                      type: integer
                      description: Unique identifier of the SKU.
                    IsMain:
                      type: boolean
                      description: Defines if the image is the main image of the SKU.
                    Label:
                      type:
                      - string
                      - 'null'
                      description: Image label.
              example:
              - Id: 1964
                ArchiveId: 155404
                SkuId: 1
                IsMain: true
                Label: ''
              - Id: 1965
                ArchiveId: 155429
                SkuId: 1
                IsMain: false
                Label: ''
  /api/catalog/pvt/stockkeepingunit/disassociate/{skuId}/file/{skuFileId}:
    delete:
      tags:
      - SKU File
      summary: VTex Disassociate SKU file
      description: 'Disassociates an SKU file from an SKU.


        ## Permissions


        Any user or [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys) must have at least one of the appropriate [License Manager resources](https://help.vtex.com/en/tutorial/license-manager-resources--3q6ztrC8YynQf6rdc6euk3) to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:


        | **Product** | **Category** | **Resource** |

        | --------------- | ----------------- | ----------------- |

        | Catalog | Content | **SKUs** |


        There are no applicable [predefined roles](https://help.vtex.com/en/tutorial/predefined-roles--jGDurZKJHvHJS13LnO7Dy) for this resource list. You must [create a custom role](https://help.vtex.com/en/tutorial/roles--7HKK5Uau2H6wxE1rH5oRbc#creating-a-role) and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see [Authentication overview](https://developers.vtex.com/docs/guides/authentication).


        >❗ To prevent integrations from having excessive permissions, consider the [best practices for managing app keys](https://help.vtex.com/en/tutorial/best-practices-application-keys--7b6nD1VMHa49aI5brlOvJm) when assigning License Manager roles to integrations.'
      parameters:
      - $ref: '#/components/parameters/Content-Type'
      - $ref: '#/components/parameters/Accept'
      - name: skuId
        in: path
        required: true
        description: SKU's unique numerical identifier.
        schema:
          type: integer
          example: 1
      - name: skuFileId
        in: path
        required: true
        description: ID of the association of the SKU and the image, which can be obtained by placing a request to the [Get SKU file](https://developers.vtex.com/vtex-rest-api/reference/catalog-api-get-sku-file) endpoint and copying the `Id` field.
        schema:
          type: integer
          example: 32
      responses:
        '200':
          description: OK
components:
  schemas:
    SKUFileURL:
      type: object
      required:
      - Name
      - Url
      properties:
        IsMain:
          type: boolean
          description: Defines if the image is the main image of the SKU.
          example: true
        Label:
          type: string
          description: SKU image label.
          example: Main
        Name:
          type: string
          description: SKU image name.
          example: Nike-Red-Janoski-1
        Text:
          type:
          - string
          - 'null'
          description: General text of the image.
          example: Nike-Red-Janoski
        Url:
          type: string
          description: External image's URL.  The URL must start with the protocol identifier (`http://` or `https://`) and end with the file extension (`.jpg`, `.png` or `.gif`).
          example: https://m.media-amazon.com/images/I/610G2-sJx5L._AC_UX695_.jpg
    SKUFile:
      type: string
      format: binary
      description: The image file has a size limit of 3200 x 3200 pixels.
  parameters:
    Content-Type:
      name: Content-Type
      in: header
      description: Type of the content being sent.
      required: true
      style: simple
      schema:
        type: string
        default: application/json
    Accept:
      name: Accept
      in: header
      description: HTTP Client Negotiation _Accept_ Header. Indicates the types of responses the client can understand.
      required: true
      style: simple
      schema:
        type: string
        default: application/json
  securitySchemes:
    appKey:
      type: apiKey
      in: header
      name: X-VTEX-API-AppKey
      description: Unique identifier of the [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys).
    appToken:
      type: apiKey
      in: header
      name: X-VTEX-API-AppToken
      description: Secret token of the [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys).
    VtexIdclientAutCookie:
      type: apiKey
      in: header
      name: VtexIdclientAutCookie
      description: '[User token](https://developers.vtex.com/docs/guides/api-authentication-using-user-tokens), valid for 24 hours.'
