openapi: 3.0.0
info:
  title: VTex Anti-fraud Provider Account Inventory API
  description: ">ℹ️ Onboarding guide\r\n>\r\n> Check the new [Payments onboarding guide](https://developers.vtex.com/docs/guides/payments-overview). We created this guide to improve the onboarding experience for developers at VTEX. It assembles all documentation on our Developer Portal about Payments and is organized by focusing on the developer's journey.\r\n\r\nThe Anti-fraud Provider Protocol is a set of definitions to help you integrate your anti-fraud service API into VTEX platform.\r\n\r\nTo achieve this, you need to implement a web API (REST) following the specifications described in this documentation.\r\n\r\n>⚠️ You can also access our [template on GitHub](https://github.com/vtex-apps/antifraud-provider-example) to help you quickly develop your anti-fraud connector using the Anti-fraud Provider Protocol and VTEX IO.\r\n\r\nTo learn more about the Anti-fraud Provider Protocol, check our [developer guide](https://developers.vtex.com/docs/guides/how-the-integration-protocol-between-vtex-and-antifraud-companies-works).\r\n\r\n## Anti-fraud Provider API Index\r\n\r\n### Anti-fraud  Flow\r\n\r\n- `POST` [Send Anti-fraud Pre-Analysis Data (optional)](https://developers.vtex.com/docs/api-reference/antifraud-provider-protocol#post-/pre-analysis)\r\n- `POST` [Send Anti-fraud Data](https://developers.vtex.com/docs/api-reference/antifraud-provider-protocol#post-/transactions)\r\n- `PUT` [Update Anti-fraud Transactions (optional)](https://developers.vtex.com/docs/api-reference/antifraud-provider-protocol#put-/transactions/-transactionId-)\r\n- `GET` [List Anti-fraud Provider Manifest](https://developers.vtex.com/docs/api-reference/antifraud-provider-protocol#get-/manifest)\r\n- `GET` [Get Anti-fraud Status](https://developers.vtex.com/docs/api-reference/antifraud-provider-protocol#get-/transactions/-transactions.id-)\r\n- `DELETE` [Stop Anti-fraud Analysis (optional)](https://developers.vtex.com/docs/api-reference/antifraud-provider-protocol#delete-/transactions/-transactions.Id-)\r\n\r\n### OAuth Flow\r\n\r\n1. `POST` [Retrieve Token](https://developers.vtex.com/docs/api-reference/antifraud-provider-protocol#post-/authorization/token)\r\n2. `GET` [Redirect](https://developers.vtex.com/docs/api-reference/antifraud-provider-protocol#get-/redirect)\r\n3. `GET` [Return to VTEX](https://developers.vtex.com/docs/api-reference/antifraud-provider-protocol#get-/authorizationCode)\r\n4. `GET` [Get Credentials](https://developers.vtex.com/docs/api-reference/antifraud-provider-protocol#get-/authorization/credentials)"
  version: '1.0'
servers:
- url: https://{providerApiEndpoint}
  description: Anti-fraud provider endpoint URL.
  variables:
    providerApiEndpoint:
      description: Anti-fraud provider endpoint URL.
      default: '{providerApiEndpoint}'
tags:
- name: Inventory
paths:
  /api/logistics/pvt/inventory/skus/{skuId}:
    get:
      tags:
      - Inventory
      summary: VTex List inventory by SKU
      description: Lists your [inventory](https://help.vtex.com/en/tutorial/inventory-management--tutorials_139) information by a SKU unique identifier (SKU ID).
      operationId: InventoryBySku
      parameters:
      - name: Content-Type
        in: header
        description: Type of the content being sent.
        required: true
        style: simple
        schema:
          type: string
          default: application/json; charset=utf-8
      - name: Accept
        in: header
        description: HTTP Client Negotiation Accept Header. Indicates the types of responses the client can understand.
        required: true
        style: simple
        schema:
          type: string
          default: application/json
      - name: skuId
        in: path
        description: Every SKU has a unique identifier called SKU ID.
        required: true
        style: simple
        schema:
          type: string
          description: '36'
      responses:
        '200':
          description: OK
          headers:
            Cache-Control:
              content:
                text/plain:
                  schema:
                    type: string
                  example: no-cache
            Content-Length:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '926'
            Date:
              content:
                text/plain:
                  schema:
                    type: string
                  example: Fri, 20 May 2016 14:11:32 GMT
            Expires:
              content:
                text/plain:
                  schema:
                    type: string
                  example: '-1'
            Pragma:
              content:
                text/plain:
                  schema:
                    type: string
                  example: no-cache
            Server:
              content:
                text/plain:
                  schema:
                    type: string
                  example: Microsoft-IIS/10.0
            X-AspNet-Version:
              content:
                text/plain:
                  schema:
                    type: string
                  example: 4.0.30319
            X-Powered-By:
              content:
                text/plain:
                  schema:
                    type: string
                  example: ASP.NET
            x-vtex-operation-id:
              content:
                text/plain:
                  schema:
                    type: string
                  example: 79a7a62f-03b8-42f8-bcb9-686bb6d67155
          content:
            application/json; charset=utf-8:
              schema:
                required:
                - skuId
                - balance
                type: object
                properties:
                  skuId:
                    type: string
                  balance:
                    type: array
                    items:
                      title: Balance
                      required:
                      - warehouseId
                      - warehouseName
                      - totalQuantity
                      - reservedQuantity
                      - hasUnlimitedQuantity
                      type: object
                      properties:
                        warehouseId:
                          type: string
                        warehouseName:
                          type: string
                        totalQuantity:
                          type: integer
                          format: int32
                        reservedQuantity:
                          type: integer
                          format: int32
                        hasUnlimitedQuantity:
                          type: boolean
                      example:
                        warehouseId: '1937054'
                        warehouseName: Estoque A
                        totalQuantity: 101
                        reservedQuantity: 9
                        hasUnlimitedQuantity: false
                    description: Array of objects with warehouses' inventory details.
                example:
                  skuId: '2390059'
                  balance:
                  - warehouseId: '1937054'
                    warehouseName: Estoque A
                    totalQuantity: 101
                    reservedQuantity: 9
                    hasUnlimitedQuantity: false
                  - warehouseId: avl
                    warehouseName: Estoque InStore
                    totalQuantity: 100
                    reservedQuantity: 0
                    hasUnlimitedQuantity: false
                  - warehouseId: 1448dc2
                    warehouseName: Estoque C
                    totalQuantity: 100
                    reservedQuantity: 0
                    hasUnlimitedQuantity: false
                  - warehouseId: 140ac66
                    warehouseName: Estoque B
                    totalQuantity: 100
                    reservedQuantity: 0
                    hasUnlimitedQuantity: false
                  - warehouseId: pickuppoint
                    warehouseName: PickupPoint
                    totalQuantity: 100
                    reservedQuantity: 0
                    hasUnlimitedQuantity: false
                  - warehouseId: pickuppoint_2
                    warehouseName: PickupPoint 2
                    totalQuantity: 200
                    reservedQuantity: 0
                    hasUnlimitedQuantity: false
                  - warehouseId: 15bfc76
                    warehouseName: Estoque Principal
                    totalQuantity: 1011
                    reservedQuantity: 0
                    hasUnlimitedQuantity: false
              example:
                skuId: '2390059'
                balance:
                - warehouseId: '1937054'
                  warehouseName: Estoque A
                  totalQuantity: 101
                  reservedQuantity: 9
                  hasUnlimitedQuantity: false
                - warehouseId: avl
                  warehouseName: Estoque InStore
                  totalQuantity: 100
                  reservedQuantity: 0
                  hasUnlimitedQuantity: false
                - warehouseId: 1448dc2
                  warehouseName: Estoque C
                  totalQuantity: 100
                  reservedQuantity: 0
                  hasUnlimitedQuantity: false
                - warehouseId: 140ac66
                  warehouseName: Estoque B
                  totalQuantity: 100
                  reservedQuantity: 0
                  hasUnlimitedQuantity: false
                - warehouseId: pickuppoint
                  warehouseName: PickupPoint
                  totalQuantity: 100
                  reservedQuantity: 0
                  hasUnlimitedQuantity: false
                - warehouseId: pickuppoint_2
                  warehouseName: PickupPoint 2
                  totalQuantity: 200
                  reservedQuantity: 0
                  hasUnlimitedQuantity: false
                - warehouseId: 15bfc76
                  warehouseName: Estoque Principal
                  totalQuantity: 1011
                  reservedQuantity: 0
                  hasUnlimitedQuantity: false
      deprecated: false
  /api/logistics/pvt/inventory/items/{skuId}/warehouses/{warehouseId}:
    get:
      tags:
      - Inventory
      summary: VTex List inventory per warehouse
      description: Lists your [inventory](https://help.vtex.com/en/tutorial/inventory-management--tutorials_139) information by warehouse.
      operationId: Inventoryperwarehouse
      parameters:
      - name: Content-Type
        in: header
        description: Type of the content being sent.
        required: true
        style: simple
        schema:
          type: string
          default: application/json; charset=utf-8
      - name: Accept
        in: header
        description: HTTP Client Negotiation Accept Header. Indicates the types of responses the client can understand.
        required: true
        style: simple
        schema:
          type: string
          default: application/json
      - name: skuId
        in: path
        description: Every SKU has a unique identifier called SKU ID.
        required: true
        style: simple
        schema:
          type: string
          description: '36'
      - name: warehouseId
        in: path
        description: Warehouse ID is the unique identifier of the [warehouse](https://help.vtex.com/en/tutorial/warehouse--6oIxvsVDTtGpO7y6zwhGpb).
        required: true
        style: simple
        schema:
          type: string
          description: warehouse-1-StoreName
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    skuId:
                      type: string
                      description: SKU ID.
                    warehouseId:
                      type: string
                      description: Warehouse ID.
                    dockId:
                      type: string
                      description: Dock ID.
                    totalQuantity:
                      type: integer
                      description: Total quantity of SKU.
                    reservedQuantity:
                      type: integer
                      description: Reserved quantity of the SKU.
                    availableQuantity:
                      type: integer
                      description: Amount of items available for sale. Difference between total quantity and reserved quantity.
                    isUnlimited:
                      type: boolean
                      description: Indicates whether the SKU's availability is unlimited ("infinite inventory").
                    salesChannel:
                      type: array
                      description: List of sales channels associated.
                      items:
                        type: string
                    deliveryChannel:
                      type: array
                      description: List of delivery channels available.
                      items:
                        type: string
                    timeToRefill:
                      type: string
                      description: Time to refill (deprecated).
                    dateOfSupplyUtc:
                      type: string
                      description: Date of supply lot in UTC.
                    keepSellingAfterExpiration:
                      type: boolean
                      description: Indicates whether SKU can continue to be sold after the available quantity gets to 0.
                    transfer:
                      type: string
                      description: Transfer.
                example:
                - skuId: '1'
                  warehouseId: '1'
                  dockId: '1'
                  totalQuantity: 1000000
                  reservedQuantity: 0
                  availableQuantity: 1000000
                  isUnlimited: true
                  salesChannel:
                  - '1'
                  deliveryChannels:
                  - delivery
                  timeToRefill: '1'
                  dateOfSupplyUtc: 12020-04-05T00:00:00+00:00
                  supplyLotId: 05-05-22
                  keepSellingAfterExpiration: false
                  transfer: Transfer 1
      deprecated: false
  /api/logistics/pvt/inventory/skus/{skuId}/warehouses/{warehouseId}:
    put:
      tags:
      - Inventory
      summary: VTex Update inventory by SKU and warehouse
      description: "Updates the [inventory](https://help.vtex.com/tutorial/inventory-management--tutorials_139) of a SKU in a given [warehouse](https://help.vtex.com/en/tutorial/warehouse--6oIxvsVDTtGpO7y6zwhGpb). This endpoint allows you to do the following:\r\n\r\n- **Define a quantity:** Indicate a specific number of SKUs, and it will decrease whenever a unit is sold. The store can eventually run out of inventory.\r\n\r\n- **Configure lead time:** Set the [lead time](https://help.vtex.com/en/tutorial/lead_time-shipping-time-at-sku-level--16yv5Mkj6bTyWR1hCN2f4B) for a given SKU from a warehouse, and this period will be added to the order total shipping time. This is an optional configuration.\r\n\r\n- **Set an infinite inventory:** Always have the SKU from the informed warehouse available for sales. The store cannot run out of inventory.\r\n\r\nSuccessful requests receive a `200 OK` with `true` in the response body. If an error occurs, you will not get a `false` string in the response body, but a message instead. For example, sending a malformatted request body will result in a  `400 Bad Request` message as a response."
      operationId: UpdateInventoryBySkuandWarehouse
      parameters:
      - name: Accept
        in: header
        description: HTTP Client Negotiation Accept Header. Indicates the types of responses the client can understand.
        required: true
        style: simple
        schema:
          type: string
          default: application/json
      - name: Content-Type
        in: header
        description: Type of the content being sent.
        required: true
        style: simple
        schema:
          type: string
          default: application/json
      - name: skuId
        in: path
        description: SKU ID is the unique identifier of the SKU you wish to update.
        required: true
        style: simple
        schema:
          type: string
          example: '25'
      - name: warehouseId
        in: path
        description: Warehouse ID is the unique identifier of the [warehouse](https://help.vtex.com/en/tutorial/warehouse--6oIxvsVDTtGpO7y6zwhGpb) associated with the SKU you wish to update.
        required: true
        style: simple
        schema:
          type: string
          example: store-warehouse
      requestBody:
        content:
          application/json:
            schema:
              title: UpdateInventoryBySkuandWarehouseRequest
              required:
              - unlimitedQuantity
              - quantity
              type: object
              properties:
                quantity:
                  type: integer
                  format: int32
                  description: "Quantity of SKU units you wish to update the [inventory](https://help.vtex.com/tutorial/inventory-management--tutorials_139) in the given [warehouse](https://help.vtex.com/en/tutorial/warehouse--6oIxvsVDTtGpO7y6zwhGpb). Note that:\r\n\r\n- Sending it as `null` sets the quantity to `0`.\r\n\r\n- Not sending it sets the quantity to `0`.\r\n\r\n- Sending `unlimitedQuantity` as `true` overrules the `quantity`."
                  nullable: true
                unlimitedQuantity:
                  type: boolean
                  description: "When set as `true`, you make the SKU from the given warehouse permanently available for sales. No matter how many units are sold, the default quantity of `1000000` units does not decrease, and the store never runs out of stock. When set as `false`, every sold unit will decrease your inventory quantity. Note that:\r\n\r\n- Sending this field as `null` sets the value to `false`.\r\n\r\n- Not sending this field sets the value to `false`.\r\n\r\n- Sending this field as `true` overrules `quantity`."
                  nullable: true
                dateUtcOnBalanceSystem:
                  type: string
                  description: "Defines the corresponding moment to the given warehouse. It is useful due to the liberation of handling order reservations.\r\n\r\nWhen set as `null`, the value will be the date/time of the request. Its format is `DateTimeOffset`, as in `yyyy-mm-dd-Thh:mm:ss`. For example: `2023-03-15T00:52:16`."
                  example: '2023-03-15T00:52:16'
                  nullable: true
                leadTime:
                  type: string
                  description: "Defines the [lead time](https://help.vtex.com/en/tutorial/lead_time-shipping-time-at-sku-level--16yv5Mkj6bTyWR1hCN2f4B), which is an optional time configuration you can make for a SKU in a warehouse. It can be handling time, fabrication or how long it takes for the item to be available to be shipped to customers.\r\n\r\nThe lead time is a part of the total shipping time and will be considered for shipping date calculation.\r\n\r\nThe format is `dd.hh:mm:ss` (days.hours:minutes:seconds). Note that:\r\n\r\n- Sending this field as `null` sets the value to `0`.\r\n\r\n- Not sending this field sets the value to `0`."
                  example: 10.23:59:15
                  nullable: true
            example:
              unlimitedQuantity: false
              dateUtcOnBalanceSystem: '2023-03-15T00:52:16'
              quantity: 101
              leadTime: 10.00:00:00
        required: true
      responses:
        '200':
          description: OK
          headers: {}
      deprecated: false
  /api/logistics/pvt/inventory/items/{skuId}/docks/{dockId}:
    get:
      tags:
      - Inventory
      summary: VTex List inventory per dock
      description: Lists your inventory information by [loading dock](https://help.vtex.com/en/tutorial/loading-dock--5DY8xHEjOLYDVL41Urd5qj).
      operationId: Inventoryperdock
      parameters:
      - name: Content-Type
        in: header
        description: Type of the content being sent.
        required: true
        style: simple
        schema:
          type: string
          default: application/json; charset=utf-8
      - name: Accept
        in: header
        description: HTTP Client Negotiation Accept Header. Indicates the types of responses the client can understand.
        required: true
        style: simple
        schema:
          type: string
          default: application/json
      - name: skuId
        in: path
        description: Every SKU has a unique identifier called SKU ID.
        required: true
        style: simple
        schema:
          type: string
          description: '36'
      - name: dockId
        in: path
        description: Dock ID is the unique identifier of the [loading dock](https://help.vtex.com/en/tutorial/loading-dock--5DY8xHEjOLYDVL41Urd5qj).
        required: true
        style: simple
        schema:
          type: string
          description: dock-13a
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    skuId:
                      type: string
                      description: SKU ID.
                    warehouseId:
                      type: string
                      description: Warehouse ID.
                    dockId:
                      type: string
                      description: Dock ID.
                    totalQuantity:
                      type: integer
                      description: Total quantity of SKU.
                    reservedQuantity:
                      type: integer
                      description: Reserved quantity of the SKU.
                    availableQuantity:
                      type: integer
                      description: Amount of items available for sale. Difference between total quantity and reserved quantity.
                    isUnlimited:
                      type: boolean
                      description: Indicates whether the SKU's availability is unlimited ("infinite inventory").
                    salesChannel:
                      type: array
                      description: List of sales channels associated.
                      items:
                        type: string
                    deliveryChannel:
                      type: array
                      description: List of delivery channels available.
                      items:
                        type: string
                    timeToRefill:
                      type: string
                      description: Time to refill (deprecated).
                    dateOfSupplyUtc:
                      type: string
                      description: Date of supply lot in UTC.
                    keepSellingAfterExpiration:
                      type: boolean
                      description: Indicates whether SKU can continue to be sold after the available quantity gets to 0.
                    transfer:
                      type: string
                      description: Transfer.
                example:
                - skuId: '1'
                  warehouseId: '1'
                  dockId: '1'
                  totalQuantity: 1000000
                  reservedQuantity: 0
                  availableQuantity: 1000000
                  isUnlimited: true
                  salesChannel:
                  - '1'
                  deliveryChannels:
                  - delivery
                  timeToRefill: 01:50:00
                  dateOfSupplyUtc: '2020-04-05T00:00:00+00:00'
                  supplyLotId: null
                  keepSellingAfterExpiration: false
                  transfer: transfer1
                - skuId: '1'
                  warehouseId: '1_1'
                  dockId: '1'
                  totalQuantity: 1000117
                  reservedQuantity: 117
                  availableQuantity: 1000000
                  isUnlimited: true
                  salesChannel:
                  - '1'
                  deliveryChannels:
                  - delivery
                  timeToRefill: 01:50:00
                  dateOfSupplyUtc: '2020-04-05T00:00:00+00:00'
                  supplyLotId: null
                  keepSellingAfterExpiration: false
                  transfer: transfer2
      deprecated: false
  /api/logistics/pvt/inventory/items/{skuId}/docks/{dockId}/warehouses/{warehouseId}:
    get:
      tags:
      - Inventory
      summary: VTex List inventory per dock and warehouse
      description: Lists your inventory information from the combination of a [loading dock](https://help.vtex.com/en/tutorial/loading-dock--5DY8xHEjOLYDVL41Urd5qj) and a [warehouse](https://help.vtex.com/en/tutorial/warehouse--6oIxvsVDTtGpO7y6zwhGpb).
      operationId: Inventoryperdockandwarehouse
      parameters:
      - name: Content-Type
        in: header
        description: Type of the content being sent.
        required: true
        style: simple
        schema:
          type: string
          default: application/json; charset=utf-8
      - name: Accept
        in: header
        description: HTTP Client Negotiation Accept Header. Indicates the types of responses the client can understand.
        required: true
        style: simple
        schema:
          type: string
          default: application/json
      - name: skuId
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      - name: dockId
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      - name: warehouseId
        in: path
        description: ''
        required: true
        style: simple
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    skuId:
                      type: string
                      description: SKU ID.
                    warehouseId:
                      type: string
                      description: Warehouse ID.
                    dockId:
                      type: string
                      description: Dock ID.
                    totalQuantity:
                      type: integer
                      description: Total quantity of SKU.
                    reservedQuantity:
                      type: integer
                      description: Reserved quantity of the SKU.
                    availableQuantity:
                      type: integer
                      description: Amount of items available for sale. Difference between total quantity and reserved quantity.
                    isUnlimited:
                      type: boolean
                      description: Indicates whether the SKU's availability is unlimited ("infinite inventory").
                    salesChannel:
                      type: array
                      description: List of sales channels associated.
                      items:
                        type: string
                    deliveryChannel:
                      type: array
                      description: List of delivery channels available.
                      items:
                        type: string
                    timeToRefill:
                      type: string
                      description: Time to refill (deprecated).
                    dateOfSupplyUtc:
                      type: string
                      description: Date of supply lot in UTC.
                    keepSellingAfterExpiration:
                      type: boolean
                      description: Indicates whether SKU can continue to be sold after the available quantity gets to 0.
                    transfer:
                      type: string
                      description: Transfer.
                example:
                - skuId: '1'
                  warehouseId: '1'
                  dockId: '1'
                  totalQuantity: 1000000
                  reservedQuantity: 0
                  availableQuantity: 1000000
                  isUnlimited: true
                  salesChannel:
                  - '1'
                  deliveryChannels:
                  - delivery
                  timeToRefill: '12:50:00'
                  dateOfSupplyUtc: '2020-04-05T00:00:00+00:00'
                  supplyLotId: null
                  keepSellingAfterExpiration: false
                  transfer: Tranfer1
      deprecated: false
  /api/logistics/pvt/inventory/items/{itemId}/warehouses/{warehouseId}/dispatched:
    get:
      tags:
      - Inventory
      summary: VTex List inventory with dispatched reservations
      description: "[Reservation](https://help.vtex.com/en/tutorial/how-does-reservation-work--tutorials_92) is the VTEX solution that prevents stores from selling the same item more than once. Adding products to the shopping cart does not create a reservation, this only happens after the shopper completes the purchase.\r\n\r\nThis endpoint lists your [inventory](https://help.vtex.com/en/tutorial/inventory-management--tutorials_139) information about dispatched reservations from a given warehouse. A reservation is considered dispatched after the order has passed the `authorize-fulfillment` status in the [order flow](https://help.vtex.com/en/tutorial/order-flow-and-status--tutorials_196) and is not canceled.\r\n\r\n**Response 400 Bad Request:** When the store has more than 2.000 active reservations, you receive a `400 Bad Request` error with the message: _Too many active reservations_"
      operationId: Getinventorywithdispatchedreservations
      parameters:
      - name: Content-Type
        in: header
        description: Type of the content being sent.
        required: true
        style: simple
        schema:
          type: string
          default: application/json; charset=utf-8
      - name: Accept
        in: header
        description: HTTP Client Negotiation Accept Header. Indicates the types of responses the client can understand.
        required: true
        style: simple
        schema:
          type: string
          default: application/json
      - name: itemId
        in: path
        description: SKU unique identifier called SKU ID. This field is an equivalent to `skuId`.
        required: true
        style: simple
        schema:
          type: string
          description: '89'
      - name: warehouseId
        in: path
        description: Warehouse ID is the unique identifier of the [warehouse](https://help.vtex.com/en/tutorial/warehouse--6oIxvsVDTtGpO7y6zwhGpb).
        required: true
        style: simple
        schema:
          type: string
          description: warehouse-1-StoreName
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    skuId:
                      type: string
                      description: SKU ID.
                    warehouseId:
                      type: string
                      description: Warehouse ID.
                    quantity:
                      type: integer
                      description: SKU quantity.
                    isUnlimitedQuantity:
                      type: boolean
                      description: Indicates whether the SKU's availability is unlimited ("infinite inventory").
                    totalReservedQuantity:
                      type: integer
                      description: Total reserved quantity of the SKU.
                    dispatchedReservationsQuantity:
                      type: integer
                      description: Dispatched reservations quantity.
                    availableQuantity:
                      type: integer
                      description: Available quantity.
                example:
                - skuId: '1'
                  warehouseId: '1'
                  quantity: 2147483647
                  isUnlimitedQuantity: true
                  totalReservedQuantity: 0
                  dispatchedReservationsQuantity: 0
                  availableQuantity: 2147483647
      deprecated: false
  /api/logistics/pvt/inventory/items/{skuId}/warehouses/{warehouseId}/supplyLots:
    get:
      tags:
      - Inventory
      summary: VTex List supply lots
      description: Returns a list of the supply lots of an SKU in a specific warehouse.
      operationId: GetSupplyLots
      parameters:
      - name: Accept
        in: header
        description: HTTP Client Negotiation Accept Header. Indicates the types of responses the client can understand.
        required: true
        style: simple
        schema:
          type: string
          example: application/json
      - name: Content-Type
        in: header
        description: Type of the content being sent.
        required: true
        style: simple
        schema:
          type: string
          example: application/json; charset=utf-8
      - name: skuId
        in: path
        description: ID of the SKU.
        required: true
        style: simple
        schema:
          type: string
      - name: warehouseId
        in: path
        description: ID of the warehouse where the SKU is located.
        required: true
        style: simple
        schema:
          type: string
      responses:
        '200':
          description: OK
          headers: {}
      deprecated: false
  /api/logistics/pvt/inventory/items/{skuId}/warehouses/{warehouseId}/supplyLots/{supplyLotId}:
    put:
      tags:
      - Inventory
      summary: VTex Save supply lot
      description: 'Creates a new Supply Lot. A Supply Lot lets the store sell products that are not currently available in stock but whose arrival is already scheduled.


        Check out our [documentation](https://help.vtex.com/en/tutorial/setting-up-future-inventory--UMSGjooqRfkRbeoh94kS4) about this feature.'
      operationId: SaveSupplyLot
      parameters:
      - name: Accept
        in: header
        description: HTTP Client Negotiation Accept Header. Indicates the types of responses the client can understand.
        required: true
        style: simple
        schema:
          type: string
          default: application/json
      - name: Content-Type
        in: header
        description: Type of the content being sent.
        required: true
        style: simple
        schema:
          type: string
          default: application/json; charset=utf-8
      - name: skuId
        in: path
        description: ID of the SKU whose availability is being scheduled.
        required: true
        style: simple
        schema:
          type: string
      - name: warehouseId
        in: path
        description: ID of the warehouse where the SKU will arrive.
        required: true
        style: simple
        schema:
          type: string
      - name: supplyLotId
        in: path
        description: ID of the Supply Lot in which the SKU's scheduling should be considered.
        required: true
        style: simple
        schema:
          type: string
      requestBody:
        content:
          application/json; charset=utf-8:
            schema:
              title: SaveSupplyLot
              required:
              - quantity
              - dateOfSupplyUtc
              - keepSellingAfterExpiration
              type: object
              properties:
                quantity:
                  type: number
                dateOfSupplyUtc:
                  type: string
                keepSellingAfterExpiration:
                  type: boolean
              example:
                quantity: 1000
                dateOfSupplyUtc: '2020-04-05T00:00:00+00:00'
                keepSellingAfterExpiration: true
            example:
              quantity: 1000
              dateOfSupplyUtc: '2020-04-05T00:00:00+00:00'
              keepSellingAfterExpiration: true
        required: true
      responses:
        '200':
          description: OK
          headers: {}
      deprecated: false
  /api/logistics/pvt/inventory/items/{skuId}/warehouses/{warehouseId}/supplyLots/{supplyLotId}/transfer:
    post:
      tags:
      - Inventory
      summary: VTex Transfer supply lot
      description: 'Transfers an SKU from a Supply Lot to the currently available inventory.


        Check out how this transfer works in further detail by reading our [documentation](https://help.vtex.com/pt/tutorial/configurar-estoque-futuro--UMSGjooqRfkRbeoh94kS4) about this feature.'
      operationId: TransferSupplyLot
      parameters:
      - name: Accept
        in: header
        description: HTTP Client Negotiation Accept Header. Indicates the types of responses the client can understand.
        required: true
        style: simple
        schema:
          type: string
          default: application/json
      - name: Content-Type
        in: header
        description: Type of the content being sent.
        required: true
        style: simple
        schema:
          type: string
          default: application/json; charset=utf-8
      - name: skuId
        in: path
        description: ID of the SKU.
        required: true
        style: simple
        schema:
          type: string
      - name: warehouseId
        in: path
        description: ID of the warehouse where the SKU is located.
        required: true
        style: simple
        schema:
          type: string
      - name: supplyLotId
        in: path
        description: ID of the Supply Lot in which the SKU is currently located and from where it will be transfered.
        required: true
        style: simple
        schema:
          type: string
      responses:
        '200':
          description: OK
          headers: {}
      deprecated: false
components:
  securitySchemes:
    VtexIdclientAutCookie:
      type: apiKey
      in: header
      name: VtexIdclientAutCookie
      description: '[User token](https://developers.vtex.com/docs/guides/api-authentication-using-user-tokens), valid for 24 hours.'
