openapi: 3.2.0
info:
  title: VTex Catalog SKU Kit API
  description: '> Check the new Catalog onboarding guide.'
  version: '1.0'
servers:
- url: https://{accountName}.{environment}.com.br
  description: VTEX server URL.
  variables:
    accountName:
      description: Name of the VTEX account. Used as part of the URL.
      default: apiexamples
    environment:
      description: Environment to use. Used as part of the URL.
      enum:
      - vtexcommercestable
      default: vtexcommercestable
security:
- appKey: []
  appToken: []
- VtexIdclientAutCookie: []
tags:
- name: SKU Kit
paths:
  /api/catalog/pvt/stockkeepingunitkit:
    get:
      tags:
      - SKU Kit
      summary: VTex Get SKU kit by SKU ID or Parent SKU ID
      description: 'Retrieves general information about the components of an SKU kit by SKU ID or Parent SKU ID.


        ## Permissions


        Any user or application key must have at least one of the appropriate License Manager resources to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:


        | **Product** | **Category** | **Resource** |

        | --------------- | ----------------- | ----------------- |

        | Catalog | Miscellaneous | **SKU Bundles** |


        There are no applicable predefined roles for this resource list. You must create a custom role and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see Authentication overview.


        >❗ To prevent integrations from having excessive permissions, consider the best practices for managing app keys when assigning License Manager roles to integrations.'
      parameters:
      - $ref: '#/components/parameters/Content-Type'
      - $ref: '#/components/parameters/Accept'
      - name: skuId
        in: query
        description: SKU's unique numerical identifier.
        required: false
        style: form
        explode: true
        schema:
          type: integer
          format: int32
          example: 1
      - name: parentSkuId
        in: query
        description: Parent SKU's unique numerical identifier.
        required: false
        style: form
        explode: true
        schema:
          type: integer
          format: int32
          example: 1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SkuKit'
              example:
                Id: 7
                StockKeepingUnitParent: 7
                StockKeepingUnitId: 1
                Quantity: 1
                UnitPrice: 50.0
      operationId: getApiCatalogPvtStockkeepingunitkit
      x-operation-id-source: derived
    post:
      tags:
      - SKU Kit
      summary: VTex Create SKU kit
      description: 'Adds a component to a specific kit.


        ## Permissions


        Any user or application key must have at least one of the appropriate License Manager resources to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:


        | **Product** | **Category** | **Resource** |

        | --------------- | ----------------- | ----------------- |

        | Catalog | Miscellaneous | **SKU Bundles** |


        There are no applicable predefined roles for this resource list. You must create a custom role and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see Authentication overview.


        >❗ To prevent integrations from having excessive permissions, consider the best practices for managing app keys when assigning License Manager roles to integrations.'
      parameters:
      - $ref: '#/components/parameters/Content-Type'
      - $ref: '#/components/parameters/Accept'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - StockKeepingUnitParent
              - StockKeepingUnitId
              - Quantity
              - UnitPrice
              properties:
                StockKeepingUnitParent:
                  type: integer
                  description: SKU ID of the SKU kit.
                  example: 31018373
                StockKeepingUnitId:
                  type: integer
                  description: Component SKU ID.
                  example: 31018374
                Quantity:
                  type: integer
                  description: Component quantity.
                  example: 3
                UnitPrice:
                  type: number
                  description: Component price per unit.
                  example: 15.5
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SkuKit'
              example:
                Id: 7
                StockKeepingUnitParent: 7
                StockKeepingUnitId: 1
                Quantity: 1
                UnitPrice: 50.0
      operationId: postApiCatalogPvtStockkeepingunitkit
      x-operation-id-source: derived
    delete:
      tags:
      - SKU Kit
      summary: VTex Delete SKU kit by SKU ID or parent SKU ID
      description: 'Deletes all kit''s components based on the parent SKU ID or deletes a specific kit''s component based on the SKU ID.


        ## Permissions


        Any user or application key must have at least one of the appropriate License Manager resources to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:


        | **Product** | **Category** | **Resource** |

        | --------------- | ----------------- | ----------------- |

        | Catalog | Miscellaneous | **SKU Bundles** |


        There are no applicable predefined roles for this resource list. You must create a custom role and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see Authentication overview.


        >❗ To prevent integrations from having excessive permissions, consider the best practices for managing app keys when assigning License Manager roles to integrations.'
      parameters:
      - $ref: '#/components/parameters/Content-Type'
      - $ref: '#/components/parameters/Accept'
      - name: skuId
        in: query
        description: SKU's unique numerical identifier.
        required: false
        style: form
        explode: true
        schema:
          type: integer
          format: int32
          example: 1
      - name: parentSkuId
        in: query
        description: Parent SKU's unique numerical identifier.
        required: false
        style: form
        explode: true
        schema:
          type: integer
          format: int32
          example: 1
      responses:
        '200':
          description: OK
      operationId: deleteApiCatalogPvtStockkeepingunitkit
      x-operation-id-source: derived
  /api/catalog/pvt/stockkeepingunitkit/{kitId}:
    get:
      tags:
      - SKU Kit
      summary: VTex Get SKU kit
      description: 'Retrieves general information about a component of a kit.


        ## Permissions


        Any user or application key must have at least one of the appropriate License Manager resources to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:


        | **Product** | **Category** | **Resource** |

        | --------------- | ----------------- | ----------------- |

        | Catalog | Miscellaneous | **SKU Bundles** |


        There are no applicable predefined roles for this resource list. You must create a custom role and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see Authentication overview.


        >❗ To prevent integrations from having excessive permissions, consider the best practices for managing app keys when assigning License Manager roles to integrations.'
      parameters:
      - $ref: '#/components/parameters/Content-Type'
      - $ref: '#/components/parameters/Accept'
      - name: kitId
        in: path
        required: true
        description: Kit's unique numerical identifier
        schema:
          type: integer
          example: 1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SkuKit'
              example:
                Id: 7
                StockKeepingUnitParent: 7
                StockKeepingUnitId: 1
                Quantity: 1
                UnitPrice: 50.0
      operationId: getApiCatalogPvtStockkeepingunitkitByKitId
      x-operation-id-source: derived
    delete:
      tags:
      - SKU Kit
      summary: VTex Delete SKU kit by kit ID
      description: 'Deletes a specific kit''s component based on its kit ID.


        ## Permissions


        Any user or application key must have at least one of the appropriate License Manager resources to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:


        | **Product** | **Category** | **Resource** |

        | --------------- | ----------------- | ----------------- |

        | Catalog | Miscellaneous | **SKU Bundles** |


        There are no applicable predefined roles for this resource list. You must create a custom role and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see Authentication overview.


        >❗ To prevent integrations from having excessive permissions, consider the best practices for managing app keys when assigning License Manager roles to integrations.'
      parameters:
      - $ref: '#/components/parameters/Content-Type'
      - $ref: '#/components/parameters/Accept'
      - name: kitId
        in: path
        required: true
        description: Kit's unique numerical identifier.
        schema:
          type: integer
          example: 1
      responses:
        '200':
          description: OK
      operationId: deleteApiCatalogPvtStockkeepingunitkitByKitId
      x-operation-id-source: derived
components:
  parameters:
    Accept:
      name: Accept
      in: header
      description: HTTP Client Negotiation _Accept_ Header. Indicates the types of responses the client can understand.
      required: true
      style: simple
      schema:
        type: string
        default: application/json
    Content-Type:
      name: Content-Type
      in: header
      description: Type of the content being sent.
      required: true
      style: simple
      schema:
        type: string
        default: application/json
  schemas:
    SkuKit:
      type: object
      properties:
        Id:
          type: integer
          description: SKU kit ID, same as `StockKeepingUnitParent`.
        StockKeepingUnitParent:
          type: integer
          description: Parent SKU ID.
        StockKeepingUnitId:
          type: integer
          description: SKU ID of the kit component.
        Quantity:
          type: integer
          description: Component quantity.
        UnitPrice:
          type: integer
          description: Component price per unit.
      example:
        Id: 7
        StockKeepingUnitParent: 7
        StockKeepingUnitId: 1
        Quantity: 1
        UnitPrice: 50.0
  securitySchemes:
    appKey:
      type: apiKey
      in: header
      name: X-VTEX-API-AppKey
      description: Unique identifier of the [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys).
    appToken:
      type: apiKey
      in: header
      name: X-VTEX-API-AppToken
      description: Secret token of the [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys).
    VtexIdclientAutCookie:
      type: apiKey
      in: header
      name: VtexIdclientAutCookie
      description: '[User token](https://developers.vtex.com/docs/guides/api-authentication-using-user-tokens), valid for 24 hours.'
