openapi: 3.2.0
info:
  title: VTex Catalog Specification Group API
  description: '> Check the new Catalog onboarding guide.'
  version: '1.0'
servers:
- url: https://{accountName}.{environment}.com.br
  description: VTEX server URL.
  variables:
    accountName:
      description: Name of the VTEX account. Used as part of the URL.
      default: apiexamples
    environment:
      description: Environment to use. Used as part of the URL.
      enum:
      - vtexcommercestable
      default: vtexcommercestable
security:
- appKey: []
  appToken: []
- VtexIdclientAutCookie: []
tags:
- name: Specification Group
paths:
  /api/catalog_system/pvt/specification/groupbycategory/{categoryId}:
    get:
      tags:
      - Specification Group
      summary: VTex List specification group by category
      description: 'Retrieves a list of specification groups by the category ID.


        ## Permissions


        Any user or application key must have at least one of the appropriate License Manager resources to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:


        | **Product** | **Category** | **Resource** |

        | --------------- | ----------------- | ----------------- |

        | Catalog | Content | **Groups** |


        There are no applicable predefined roles for this resource list. You must create a custom role and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see Authentication overview.


        >❗ To prevent integrations from having excessive permissions, consider the best practices for managing app keys when assigning License Manager roles to integrations.'
      operationId: SpecificationsGroupListbyCategory
      parameters:
      - $ref: '#/components/parameters/Content-Type'
      - $ref: '#/components/parameters/Accept'
      - name: categoryId
        in: path
        description: Category ID.
        required: true
        style: simple
        schema:
          type: string
          example: '1'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/SpecificationsGroup'
              example:
              - CategoryId: 1
                Id: 5
                Name: Materials
                Position: 2
              - CategoryId: 1
                Id: 6
                Name: Sizes
                Position: 3
      deprecated: false
  /api/catalog_system/pub/specification/groupGet/{groupId}:
    get:
      tags:
      - Specification Group
      summary: VTex Get specification group
      description: 'Retrieves details from a specification group by the ID of the group.


        ## Permissions


        Any user or application key must have at least one of the appropriate License Manager resources to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:


        | **Product** | **Category** | **Resource** |

        | --------------- | ----------------- | ----------------- |

        | Catalog | Content | **Groups** |


        There are no applicable predefined roles for this resource list. You must create a custom role and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see Authentication overview.


        >❗ To prevent integrations from having excessive permissions, consider the best practices for managing app keys when assigning License Manager roles to integrations.'
      operationId: SpecificationsGroupGet
      parameters:
      - $ref: '#/components/parameters/Content-Type'
      - $ref: '#/components/parameters/Accept'
      - name: groupId
        in: path
        description: Specification group ID.
        required: true
        style: simple
        schema:
          type: string
          example: '6'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SpecificationsGroup'
              example:
                CategoryId: 1
                Id: 6
                Name: Sizes
                Position: 3
      deprecated: false
  /api/catalog/pvt/specificationgroup:
    post:
      tags:
      - Specification Group
      summary: VTex Create specification group
      description: 'Create a specification group.

        >⚠️ It is also possible to create a specification Group by using an alternative legacy route: `/api/catalog_system/pvt/specification/group`.


        ## Permissions


        Any user or application key must have at least one of the appropriate License Manager resources to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:


        | **Product** | **Category** | **Resource** |

        | --------------- | ----------------- | ----------------- |

        | Catalog | Content | **Groups** |


        There are no applicable predefined roles for this resource list. You must create a custom role and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see Authentication overview.


        >❗ To prevent integrations from having excessive permissions, consider the best practices for managing app keys when assigning License Manager roles to integrations.'
      operationId: SpecificationGroupInsert2
      parameters:
      - $ref: '#/components/parameters/Content-Type'
      - $ref: '#/components/parameters/Accept'
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SpecificationGroupInsertRequest'
            example:
              CategoryId: 1
              Name: Sizes
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  Id:
                    type: integer
                    format: int32
                    description: Specification group ID.
                  CategoryId:
                    type: integer
                    format: int32
                    description: Category ID.
                  Name:
                    type: string
                    description: Specification group name.
                  Position:
                    type: integer
                    format: int32
                    description: 'Store Framework - Deprecated.

                      Legacy CMS Portal - specification Group Position.'
              example:
                Id: 10
                CategoryId: 1
                Name: Sizes
                Position: 3
      deprecated: false
  /api/catalog/pvt/specificationgroup/{groupId}:
    put:
      tags:
      - Specification Group
      summary: VTex Update specification group
      description: 'Update a specification group.

        >⚠️ It is also possible to update a specification Group by using an alternative legacy route: `/api/catalog_system/pvt/specification/group`.


        ## Permissions


        Any user or application key must have at least one of the appropriate License Manager resources to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:


        | **Product** | **Category** | **Resource** |

        | --------------- | ----------------- | ----------------- |

        | Catalog | Content | **Groups** |


        There are no applicable predefined roles for this resource list. You must create a custom role and add at least one of the resources above in order to use this endpoint. To learn more about machine authentication at VTEX, see Authentication overview.


        >❗ To prevent integrations from having excessive permissions, consider the best practices for managing app keys when assigning License Manager roles to integrations.'
      parameters:
      - $ref: '#/components/parameters/Content-Type'
      - $ref: '#/components/parameters/Accept'
      - name: groupId
        in: path
        required: true
        description: Group's unique numerical identifier.
        schema:
          type: integer
          example: 1
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
              - CategoryId
              - Name
              - Id
              - Position
              properties:
                CategoryId:
                  type: integer
                  description: Category ID where the specification group is contained.
                  example: 1
                Id:
                  type: integer
                  format: int32
                  description: Specification group ID.
                  example: 24
                Name:
                  type: string
                  description: Specification group name.
                  example: Sizes
                Position:
                  type: integer
                  description: Specification group position.
                  example: 1
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  CategoryId:
                    type: integer
                    description: Category ID where the specification Group is contained.
                    example: 1
                  Id:
                    type: integer
                    format: int32
                    description: Specification group ID.
                    example: 24
                  Name:
                    type: string
                    description: Specification group Name.
                    example: Sizes
                  Position:
                    type: integer
                    description: Specification group Position.
                    example: 1
      operationId: putApiCatalogPvtSpecificationgroupByGroupId
      x-operation-id-source: derived
components:
  parameters:
    Accept:
      name: Accept
      in: header
      description: HTTP Client Negotiation _Accept_ Header. Indicates the types of responses the client can understand.
      required: true
      style: simple
      schema:
        type: string
        default: application/json
    Content-Type:
      name: Content-Type
      in: header
      description: Type of the content being sent.
      required: true
      style: simple
      schema:
        type: string
        default: application/json
  schemas:
    SpecificationGroupInsertRequest:
      required:
      - CategoryId
      - Name
      type: object
      properties:
        CategoryId:
          type: integer
          format: int32
          description: Category ID.
        Name:
          type: string
          description: Specification group name.
      example:
        CategoryId: 1
        Name: GroupName1
    SpecificationsGroup:
      required:
      - CategoryId
      - Id
      - Name
      - Position
      type: object
      properties:
        CategoryId:
          type:
          - integer
          - 'null'
          description: Category ID.
        Id:
          type: integer
          format: int32
          description: Specification group ID.
        Name:
          type: string
          description: Specification group name.
        Position:
          type:
          - integer
          - 'null'
          format: int32
          description: Specification group position.
      example:
        CategoryId: 1
        Id: 4
        Name: Sizes
        Position: 1
  securitySchemes:
    appKey:
      type: apiKey
      in: header
      name: X-VTEX-API-AppKey
      description: Unique identifier of the [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys).
    appToken:
      type: apiKey
      in: header
      name: X-VTEX-API-AppToken
      description: Secret token of the [application key](https://developers.vtex.com/docs/guides/api-authentication-using-application-keys).
    VtexIdclientAutCookie:
      type: apiKey
      in: header
      name: VtexIdclientAutCookie
      description: '[User token](https://developers.vtex.com/docs/guides/api-authentication-using-user-tokens), valid for 24 hours.'
